### ISSUE TITLE
What does ops folder use for?

### ISSUE THREAD

**Issue by kasrasaeed** [eminetto/clean-architecture-go-v2#14]
Hi, thanks for great implementation.
Can you explain what does the ops folder use for?
And also as a recommendation, you can add log folder too.

**Comment by eminetto** [comment]
In the folder `ops` I'm storing the configuration about the `ops` in the  `DevOps`  :) Prometheus configuration, database creation scripts, and so on

**Comment by kasrasaeed** [comment]
Thanks.
